wunderio/silta-cli

.github/workflows/master.yml, .github/workflows/release.yml, .github/workflows/test.yml
- Attaches feature branch test binaries to "test" release
- Builds and attaches windows and os/x (darwin) binaries to master and test releases. Darwin binaries are unsigned at the moment, can't be run without extra signing process
- Builds and attaches windows binaries to standard releases
- Builds arm64 arch binaries
=> Cross compiled binary builds for linux and windows

cmd/ciReleaseName.go, internal/common/ciReleaseEnvironmentname.go, tests/release-name.sh, tests/release_test.go
Existing release name trimming is broken and allows unlimited release name length (helm will return error, but it's still inconsistent).
=> Release name length fix

cmd/ciReleaseDeploy.go, cmd/ciReleaseValidate.go, tests/release_test.go
Updates `show_failing_pods fuction` so it would print logs and events of failed containers. Creates trap that prints logs during other build failures too.
Test builds: https://app.circleci.com/pipelines/github/wunderio/drupal-project-k8s?branch=feature%2Fslt-778-failed-build-log
=> Print event and logs for failing pods during deployment

cmd/ciImageBuild.go, cmd/ciImageUrl.go
output from tar is passed to golang for checksum calculation. we pass it back to bash to avoid unnecessary memory usage
=> fix memory usage by calculating file checksum in bash instead of piping output to golang

cmd/ciReleaseDelete.go
Removes leftover post-release job pods.
> W1221 09:22:42.122073 1491390 warnings.go:70] child pods are preserved by default when jobs are deleted; set propagationPolicy=Background to remove them or set propagationPolicy=Orphan to suppress this warning
=> Remove existing pods for post-release when removing job.

cmd/ciImageBuild.go, cmd/ciImageUrl.go
Adds an --image-tag-prefix option to define a prefix for container image tags.
Follows the logic of image tags - if image tag prefix is an empty string, it gets ignored.
=> Prefix option

cmd/ciReleaseWakeup.go, docs/silta_ci_release.md, docs/silta_ci_release_wakeup.md
Output example:
```
silta ci release wakeup --namespace drupal-project-k8s --release-name example
2024/01/11 16:51:32 Scaling deployments
2024/01/11 16:51:32 Scaling example-drupal to 1 replica(s)
2024/01/11 16:51:32 Scaling example-shell to 1 replica(s)
2024/01/11 16:51:32 Scaling example-varnish to 1 replica(s)
2024/01/11 16:51:43 Scaling statefulsets
2024/01/11 16:51:43 Scaling example-es to 1 replica(s)
2024/01/11 16:51:43 Scaling example-mariadb to 1 replica(s)
2024/01/11 16:53:05 Resuming cronjobs
2024/01/11 16:53:05 Unpausing example-cron-drupal
2024/01/11 16:53:05 Restoring services
2024/01/11 16:53:05 Resetting example-varnish
2024/01/11 16:53:05 Reset example-varnish to original service
2024/01/11 16:53:06 https://example.drupal-project-k8s.silta-test.wdr.io
```
=> Wake up a downscaled release

cmd/ciReleaseDeploy.go, tests/release_test.go
This PR reenables `--wait` flag for `helm install / upgrade`. The process itself runs in background anyway and it's pid is watched for timeouts and error printing. 
It's required for proper post-release hook timing, as per [doc](https://helm.sh/docs/topics/charts_hooks/), 
>  if the `--wait` flag is set, the library will wait until all resources are in a ready state and will not run the post-install hook until they are ready.
This should solve the issue where postinstall clears caches, but there's a chance web request to old (non-replaced) replica is hit and it generates module cache from old webroot.
This was tested with both succeeding and failing deployments for drupal and frontend chart, no regressions spotted.
=> Add --wait flag for helm release to enable proper post-release creation

cmd/ciReleaseDeploy.go, tests/release_test.go
**Reasoning:** Currently it does not matter if deployment_timeout is set to 15m in silta orb. Deployment exits with "Timeout waiting for resources" after 300 seconds ignoring deployment_timeout.
**Features:**
- Converts already used deploymentTimout to integer of seconds
- Uses deploymentTimoutSeconds as comparison for $TIME_WAITING
=> Use provided deployment timeout to timeout

cmd/ciReleaseDeploy.go
Allows setting repository to empty string  (for oci repositories), still defaults to previous version.
=> Do not force chart repository

cmd/ciImageBuild.go, cmd/ciReleaseCleanfailed.go, cmd/ciReleaseDeploy.go, cmd/ciReleaseInfo.go, cmd/ciReleaseValidate.go, cmd/ciToolsCheck.go, cmd/root.go
docker image build in cci returns build logs into stderr. this pr tackles docker build wrapper case, removes "ERROR: " prefix.
=> Remove "ERROR:" prefix from docker image builds

cmd/ciReleaseWakeup.go, cmd/config.go, cmd/configGet.go, cmd/configSet.go, cmd/root.go, go.mod, go.sum, internal/common/config.go
- Provides `config get` and `config set` commands
- Provides persistent configuration storage.
- Linux location: `/home/<user>/.config/silta/`
- Windows location: `C:\Users\<user>\AppData\Local\silta\`
- Mac OS location: `/Users/<user>/Library/Application Support/silta/`
- Sets http proxy environment variables in application scope whenever a non-empty `proxy` configuration item is found
Testing:
1. Set context to a cluster that requires connection
2. Load release information via `silta ci release info --release-name <release-name> --namespace <namespace>`. Should fail.
3. Set proxy configuration `silta config set proxy localhost:1234` (do not create tunnel yet).
4. Load release information again. Should fail again but with a message "proxyconnect tcp: dial tcp [::1]:1234: connect: …
=> Persistent configuration; Load and use proxy configuration.

cmd/ciReleaseDeploy.go, cmd/ciReleaseValidate.go
In order for https://github.com/wunderio/silta-circleci/pull/197 to work properly, helm repos need to be up to date
=> Make sure helm repos are up to date

cmd/ciReleaseDiff.go, cmd/ciScripts.go, cmd/ciScriptsEsInitRemove.go
- Release diff command
- Elasticsearch init container removal script
=> release diff; es init container removal script

cmd/ciReleaseDeploy.go, cmd/ciReleaseDiff.go
Does lookup for both old and new reference PVC names before setting `skipMount: false`.
=> Reference PVC lookup adjustment

cmd/ciReleaseCleanfailed.go, cmd/ciReleaseDelete.go, cmd/ciReleaseDeploy.go, internal/common/ciReleaseFunctions.go
Separate deployment removal function that can be reused by importing common package.
=> Removal and cleanup deduplication

cmd/ciCloudLogin.go, cmd/ciReleaseDeploy.go, tests/cloud_test.go, tests/release_test.go
- Test connection after cloud login
- [chore] Remove release log
=> test connection after cloud login, remove failed release log

cmd/ciImageLogin.go, tests/image_test.go
Adds single quote instead of double quote to avoid parsing parameters (fixes issue where username contains dollar sign)
=> Quote docker login parameters

cmd/ciReleaseCleanfailed.go, cmd/ciReleaseDelete.go, cmd/ciReleaseDeploy.go, cmd/ciReleaseDiff.go, cmd/ciReleaseList.go, cmd/ciReleaseValidate.go, cmd/ciReleaseWakeup.go, cmd/ciScriptsEsInitRemove.go
This mirrors behavior of other cli tools where `KUBECONFIG` environment variable takes precedence for kubeconfig location.
=> Use KUBECONFIG environment variable first

cmd/ciReleaseCleanfailed.go, cmd/ciReleaseDelete.go, cmd/ciReleaseDeploy.go, cmd/ciReleaseDiff.go, cmd/ciReleaseList.go, cmd/ciReleaseWakeup.go, cmd/ciScriptsEsInitRemove.go, go.mod, go.sum, internal/common/ciReleaseFunctions.go, internal/common/kube.go
Replaces https://pkg.go.dev/github.com/mittwald/go-helm-client library with official helm library
=> Use official helm library
